server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: k-rest-proxy

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: k-rest-proxy-group
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081

app:
  security:
    api-key: "secret-api-key" # Change this in production
